apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: python-deployment
  name: python-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-deployment
    spec:
      containers:
      - image: abhiramikannan/python-image
        name: python-image
        resources: {}
status: {}
