apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-deployment
  name: python-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 5000
  selector:
    app: python-deployment
  type: NodePort
status:
  loadBalancer: {}
